# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170714_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='app01.Tag'),
        ),
    ]
